Fri 21
friday-night-commit/2048-game pull request #13
Opened 2023-04-26 15:11 UTC by laksan1

### Какую задачу решаем
Сделана страница профиля пользователя и модальное окно для смены пароля.

### Скриншоты/видяшка (если есть)
![image](https://user-images.githubusercontent.com/53944188/234619591-6833a658-580a-4e17-b857-66e84960a0a4.png)
![image](https://user-images.githubusercontent.com/53944188/234619692-479eda5f-48d0-4430-9e57-d9f19b46ac75.png)

### TBD (если есть)

2023-04-26 19:46 UTC, julia-aranovich commented on packages/client/src/pages/Profile/index.tsx
> +      <Card color='white' className='p-12 max-w-md w-full' shadow={false}>
<Card /> обертка уже содержится в  CardContainer  строкой выше

2023-04-26 19:48 UTC, julia-aranovich commented on packages/client/src/pages/Profile/index.tsx
> +      <div> {visibilityChangePasswordModal &&
div-обертка и проверка visibilityChangePasswordModal не нужны, можно просто оставить `<ChangePasswordModal ... />` и он сам отобрзаится/скроется, когда надо, не нарушая верстки

2023-04-26 19:50 UTC, julia-aranovich commented on packages/client/src/index.scss
> +.avatar-container {
Эти стили надо оставить в  scss  файле  Avatar компоненты. Почистила данный  index.scss  файл в своих обновленных ветках (.game-button  и пр унесены в стили  PageContainer компоненты)

2023-04-27 13:06 UTC, julia-aranovich commented on packages/client/src/pages/Profile/index.tsx
> +      <Form className='w-full'
Николай в ревью Алексея просил вынести форму в отдельный компонент, чтобы страница знала только, что она содержит какую-то форму.

2023-04-27 19:10 UTC, julia-aranovich commented on packages/client/src/Components/Input/index.tsx
> +    <label className="form__label">
Для чего эта обертка в label? Не будет ли в итоговом html два <label /> на каждый инпут?

2023-04-27 19:10 UTC, julia-aranovich commented on packages/client/src/pages/Profile/components/ChangePassword/ChangePassword.tsx
> +  const containerRef = useRef(null);
Для чего этот реф? Как планируется использовать?

2023-04-27 19:10 UTC, julia-aranovich commented on packages/client/src/pages/Profile/index.tsx
> +  const handleOpenChangePasswordModal = () => setVisibilityChangePasswordModal(prev => !prev)
Дублирует функцию openChangePasswordModal

2023-04-27 19:10 UTC, julia-aranovich commented on packages/client/src/pages/Profile/index.tsx
> +          <Button
Точно нужна эта кнопка? Пользователь может нажать на лого в верхнем левом углу, чтобы попасть на главную страницу. Или воспользоваться навбаром, чтобы уйти на другие страницы

2023-04-27 19:10 UTC, julia-aranovich commented on packages/client/src/router.tsx
> -  [
Пожалуйста, верни задание путей через список объектов, это было согласовано с Николаем в Лешином ревью

2023-04-27 19:10 UTC, julia-aranovich commented on packages/client/src/pages/Profile/components/ChangePassword/ChangePassword.tsx
> +                onClick={onClose}
здесь достаточно в  onClick передать handleOpen, он закроет открытую модалку. onClose  пропс в данном случае излишний

2023-05-02 19:51 UTC, julia-aranovich commented on packages/client/src/Components/Form/index.tsx
> +  handlerSubmit: (e: FormEvent<HTMLFormElement>) => void;
Более правильно назвать handleSubmit

2023-05-02 19:51 UTC, julia-aranovich commented on packages/client/src/Components/Input/index.tsx
> +    console.log('handleError', e);
Мб испольщовать setError здесь?

2023-05-02 19:51 UTC, julia-aranovich commented on packages/client/src/Utils/Validators/InputValidator.ts
> +    return this.errors[0] ? this.errors[0] : '';
`return this.errors[0] || '';`

2023-05-02 19:51 UTC, julia-aranovich commented on packages/client/src/pages/Profile/index.tsx
> +export enum UserFields {
Этот Enum используется только в ProfileForm, мб там же его и объявлять? UserFields  по смыслу относятся непосредственно к ProfileForm

2023-05-02 19:51 UTC, julia-aranovich commented on packages/client/src/pages/Profile/components/ChangePassword/ChangePassword.tsx
> +enum PASSWORDS_TYPE {
Лучше назвать Enum-ы с полями в одном ключе. Сейчас PASSWORDS_TYPE и UserFields. Может тогда (Change)PasswordFields?

2023-05-02 19:51 UTC, julia-aranovich commented on packages/client/src/pages/Profile/components/ChangePassword/ChangePassword.tsx
> +  onClose?: () => void;
Этот пропс нигде не используется

2023-05-02 19:51 UTC, julia-aranovich commented on packages/client/src/pages/Profile/components/ChangePassword/ChangePassword.tsx
> +      const repeatPassword = (
FYI: в ревью Лешиного пиара Николай рекомендовал хранить данные формы в стейте. Для лучшей типизации, и были еще аргументы За

2023-05-02 19:51 UTC, julia-aranovich commented on packages/client/src/pages/Profile/components/ChangePassword/ChangePassword.tsx
> +            required={true}
required  свойство описывается в Validator-е. То есть строки `required={true}` у инпутов в таком случае не нужны.

P.S. Можно просто писать `required` (вместо  `required={true}`)

2023-05-02 19:51 UTC, julia-aranovich commented on packages/client/src/Components/Avatar/index.tsx
> +      {error && <Toast text={error} />}
Toast используется только для отображения ошибок. Может нам будет достаточно Alert компоненты из material-tailwind? Она уже стилизована под остальной ui

2023-05-02 19:51 UTC, julia-aranovich commented on packages/client/src/Components/Input/index.tsx
> +        <input
Я все еще голосую за Input из  material-tailwind: он выглядит красивее, сверстан с анимацией и тд. К нему точно также можно написать нужную обертку. Это не блочит ревью, но давайте уже договормся/проголосуем?

В AuthForm надо будет поправить на новые инпуты тогда тоже. Чтобы везде было одинаково.

2023-05-02 19:51 UTC, julia-aranovich commented on packages/client/src/Components/Input/index.tsx
> +    <div className="initial-input">
`custom-input`, `2048-input` ?..  `initial-input` выглядит как "первоначальный инпут" (IMHO)

2023-05-02 19:51 UTC, julia-aranovich commented on packages/client/src/Components/ProfileForm/index.tsx
> +    <Form className="w-full" handlerSubmit={handleSubmit}>
Мучаюсь в догадках, как двойные кавычки проходят линтер? У нас там выставлено строго на одинарные

2023-05-02 19:51 UTC, julia-aranovich commented on packages/client/src/pages/Profile/index.tsx
> +        Настройки профиля
Стоит назвать страницу также как в навбаре. Переименовать тут, либо в навбаре

2023-05-02 19:51 UTC, julia-aranovich commented on packages/client/src/Components/ProfileForm/index.tsx
> +        <Button
Давайте верстать в одном ключе. Тут лучше сделать ссылкой как здесь https://github.com/friday-night-commit/2048-game/blob/dev/packages/client/src/Components/AuthForm/AuthForm.tsx#L63
А то тут выходит 3 равнозначные разноцветные кнопки

2023-05-02 19:51 UTC, julia-aranovich commented on packages/client/src/Components/ProfileForm/index.tsx
> +          className="small game-button">
А эту кнопку сделала бы amber цветом. `game-button`  класс меняет маржины и добавляет коричневый цвет, который пока у нас используется только на страницах  игры

2023-05-03 07:14 UTC, laksan1 commented on packages/client/src/Components/Input/index.tsx
> +    console.log('handleError', e);
сейчас, подумал, что это лишнее. У меня ошибка выводится тут  **<span className="initial-input__error">{error}</span>** , больше не нужна

2023-05-03 07:26 UTC, laksan1 commented on packages/client/src/pages/Profile/index.tsx
> +export enum UserFields {
вынес в папку models

2023-05-03 07:30 UTC, laksan1 commented on packages/client/src/pages/Profile/components/ChangePassword/ChangePassword.tsx
> +      const repeatPassword = (
Я же это сделал, как заглушку, чтобы показать обработку ошибок. Когда данные будут приходить через fetch, то там будет стейт.

2023-05-03 09:17 UTC, laksan1 commented on packages/client/src/Components/ProfileForm/index.tsx
> +    <Form className="w-full" handlerSubmit={handleSubmit}>
вот так
![image](https://user-images.githubusercontent.com/53944188/235877652-81319220-34de-4eea-8a91-528da6492f1c.png)

2023-05-03 11:25 UTC, julia-aranovich approved these changes
- Поправь плиз AuthForm инпуты для однородности
- UserFields будут использоваться также на AuthPage, RegisterPage - мб вынести их куда-то вне  Profile страницы? Плюс, немного смущает папка  models - что там будет лежать, какие модели?
- валидаторы я бы положила просто в validators папку, без utils - хочется избавиться от глубокой вложенности
- не нравится, что у нас сейчас какие-то папки с большой буквы именуются, какие-то с маленькой...

2023-05-03 11:25 UTC, julia-aranovich commented on packages/client/src/Components/Avatar/index.tsx
> +      <div className="avatar-container">
Есть догадки насчет линтера?) Почему он проходит на двойных кавычках? У нас прописаны одинарные

2023-05-03 11:25 UTC, julia-aranovich commented on packages/client/src/Components/Input/index.scss
> +  &__label {
В текущей верстке нет этого класса

2023-05-03 11:25 UTC, julia-aranovich commented on packages/client/src/Components/Input/index.scss
> +  display: flex;
В текущей верстке нет класса `.default-input`, поэтом стили в сроках 4-6 не применяются

2023-05-03 11:25 UTC, julia-aranovich commented on packages/client/src/Components/Input/index.tsx
> +        className='px-5 py-2 rounded-full outline-none'
`rounded-full` класс приводит к глюку в верстке инпута в фокусе:
![Screenshot 2023-05-03 at 15 11 55](https://user-images.githubusercontent.com/123967434/235901801-4520e91a-be71-40dd-bd87-91cb6ef3a52d.png)

2023-05-03 11:25 UTC, julia-aranovich commented on packages/client/src/Utils/Validators/InputValidator.ts
> +      this._addInvalidity('Поле обязательно для заполнения');
Я бы не стала выводить это сообщение. У нас есть звездочки, обозначающие обязательное поле, и при сабмите формы браузер также выводит соответствующую подсказку. Выглядит, что этого достаточно

2023-05-03 11:28 UTC, julia-aranovich commented on packages/client/src/Components/ProfileForm/index.tsx
> +          to={routes.gamePage}
Если оставить лейбл "Вернуться назад", то лучше вернуть `navigate(-1)`, чтобы действие соответствовало названию. 
Или тогда переименовать в "На главную" и отправлять на `routes.mainPage`,  мы с нее стартуем игру

2023-05-03 12:22 UTC, Delexy commented on packages/client/src/Components/Avatar/index.tsx
> +      <div className="avatar-container">
Я добавил правило, сейчас должен корректно отрабатывать (добавлено в ветке со страницей лидеров)

2023-05-03 12:25 UTC, Delexy approved these changes

2023-05-08 17:17 UTC, Brarion requested changes
Один вопросик оставил

2023-05-08 17:17 UTC, Brarion commented on packages/client/src/Components/Form/index.tsx
> +export default Index;
А в чём смысл этого компонента?

2023-05-12 09:36 UTC, laksan1 commented on packages/client/src/Components/Form/index.tsx
> +export default Index;
мы его удалили

2023-05-12 11:37 UTC, Brarion approved these changes

2023-05-12 11:39 UTC, merged