2048game add canvas
friday-night-commit/2048-game pull request #18
Opened 2023-04-30 18:53 UTC by yppix

### Какую задачу решаем
Игровая механика

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-05-01 04:05 UTC, EzhikTT commented on packages/client/src/Components/Game/utils/createCell.tsx
> +  getValue() {
https://www.typescriptlang.org/docs/handbook/2/classes.html#getters--setters

2023-05-01 04:07 UTC, EzhikTT commented on packages/client/src/Components/Game/utils/createCell.tsx
> +function getCellPosition() {
Почему эти методы не в классе?

2023-05-01 04:07 UTC, EzhikTT commented on packages/client/src/Components/Game/utils/createCell.tsx
> +  return Math.random() > 0.75 ? 4 : 2
Это что за магия?)

2023-05-01 04:08 UTC, EzhikTT commented on packages/client/src/Components/Game/utils/createCell.tsx
> +      default:
Можно без дефолта тут, логики-то нет. А ретурн вынести в конец всего метода

2023-05-01 04:09 UTC, EzhikTT commented on packages/client/src/Components/Game/utils/moveMatrixElements.ts
> +export default function moveMatrixElements(moveDirection: string, context: CanvasRenderingContext2D) {
Этот метод должен быть в глобальном классе игры(движка)

2023-05-01 04:11 UTC, EzhikTT commented on packages/client/src/Components/Game/utils/createCell.tsx
> +export class Cell {
В этом файле главный - класс, а не метод. Название файла не правильное

2023-05-01 13:59 UTC, yppix commented on packages/client/src/Components/Game/utils/createCell.tsx
> +  return Math.random() > 0.75 ? 4 : 2
рандомное получение значения ячейки - либо 2 либо 4

2023-05-02 10:56 UTC, julia-aranovich commented on packages/client/src/Components/Game/Engine/Engine.tsx
> +  generateRandom(min = 0, max = 100) {
В lodash  есть random  функция, вроде

2023-05-05 04:32 UTC, EzhikTT commented on packages/client/src/Components/Game/Cell/Cell.tsx
> +  getValue(): number {
Нужны нормальный get/set или ацессоры (раньше скидывал)

2023-05-05 04:33 UTC, EzhikTT commented on packages/client/src/Components/Game/Cell/Cell.tsx
> +  private generateValue(): number {
Возможно, стоит сделать его статичным и перенести в игру или утилиту

2023-05-05 04:34 UTC, EzhikTT commented on packages/client/src/Components/Game/Cell/Cell.tsx
> +    this.context.font = "20px Arial";
Это не нужно делать на каждом рендере. Можно только при создании ячейки настраивать

2023-05-05 04:35 UTC, EzhikTT commented on packages/client/src/Components/Game/Engine/Engine.tsx
> +    this.cells = [];
Возможно, можно вынести это тоже в определение для инициализации

2023-05-05 04:35 UTC, EzhikTT commented on packages/client/src/Components/Game/Engine/Engine.tsx
> +  static generateRandom(min = 0, max = 100) {
Если оно не относится напрямую к игре - убери в утилиты

2023-05-05 04:36 UTC, EzhikTT commented on packages/client/src/Components/Game/Engine/Engine.tsx
> +    const randomCoordinates = this.generateRandomCellPosition();
В чем смысл существования этой строчки отдельно?

2023-05-05 04:37 UTC, EzhikTT commented on packages/client/src/Components/Game/Engine/Engine.tsx
> +    return matrix.reduce((emptyCoordinates: any, matrixLine, y: number) => {
А что за `matrix`?

2023-05-05 04:38 UTC, EzhikTT commented on packages/client/src/Components/Game/Engine/Engine.tsx
> +      matrixLine.forEach((elem: number, x: number) => {
используй человеческие циклы

2023-05-05 04:39 UTC, EzhikTT commented on packages/client/src/Components/Game/Engine/Engine.tsx
> +    if (moveDirection === Direction.LEFT) {
Можно было оставить `switch..case`

2023-05-05 04:39 UTC, EzhikTT commented on packages/client/src/Components/Game/Engine/Engine.tsx
> +        if(cellPositionX) {
А если она 0?

2023-05-05 04:42 UTC, EzhikTT commented on packages/client/src/Components/Game/Engine/Engine.tsx
> +      this.cells.forEach((item) => {
Вот кто вас этому научил?

2023-05-05 04:42 UTC, EzhikTT commented on packages/client/src/Components/Game/Canvas/Canvas.tsx
> +      engine.createListeners()
Это можно в конструктуре сделать. Не нужно показывать это всем

2023-05-05 04:43 UTC, EzhikTT commented on packages/client/src/Components/Game/Engine/Engine.tsx
> +  moveMatrixElements(moveDirection: Direction): void {
Очень плохой метод и неоптимальный. Нужно что-то порешать

2023-05-05 04:44 UTC, EzhikTT commented on packages/client/src/Components/Game/Engine/Engine.tsx
> +        cell.render()
Можно просто проверять наличие метода

2023-05-05 10:34 UTC, yppix commented on packages/client/src/Components/Game/Engine/Engine.tsx
> +        if(cellPositionX) {
не будет сдвига и в этом  и суть

2023-05-05 10:36 UTC, yppix commented on packages/client/src/Components/Game/Engine/Engine.tsx
> +    const randomCoordinates = this.generateRandomCellPosition();
дальше используется в функции?

2023-05-05 10:56 UTC, yppix commented on packages/client/src/Components/Game/Canvas/Canvas.tsx
> +      engine.createListeners()
+

2023-05-05 10:57 UTC, yppix commented on packages/client/src/Components/Game/Engine/Engine.tsx
> +  static generateRandom(min = 0, max = 100) {
+

2023-05-05 10:57 UTC, yppix commented on packages/client/src/Components/Game/Cell/Cell.tsx
> +  private generateValue(): number {
+

2023-05-05 13:27 UTC, yppix commented on packages/client/src/Components/Game/Cell/Cell.tsx
> +  getValue(): number {
пуе реализовала, для set получаю - Type 'Position' has no call signatures. 
Поэтому set вернула

2023-05-05 13:40 UTC, yppix commented on packages/client/src/Components/Game/Engine/Engine.tsx
> +    this.cells = [];
?

2023-05-05 14:01 UTC, yppix commented on packages/client/src/Components/Game/Engine/Engine.tsx
> +    return matrix.reduce((emptyCoordinates: any, matrixLine, y: number) => {
const matrix: number[][] = Array.from({ length: 4 }, () =>
  Array.from({ length: 4 }, () => 0)
);

line: 221

по факту матрица осталась, может через нее раз так удобнее? но как тогда?

2023-05-05 16:13 UTC, yppix commented on packages/client/src/Components/Game/Engine/Engine.tsx
> +    if (moveDirection === Direction.LEFT) {
+

2023-05-05 16:38 UTC, yppix commented on packages/client/src/Components/Game/Cell/Cell.tsx
> +    this.context.font = "20px Arial";
?

2023-05-05 16:38 UTC, yppix commented on packages/client/src/Components/Game/Engine/Engine.tsx
> +        cell.render()
?

2023-05-06 04:32 UTC, EzhikTT commented on packages/client/src/Components/Game/Canvas/Canvas.tsx
> +      if (!canvas) {
В данном случае лучше не использовать ретурны, чтобы прерывать хук. Сделай вложенные ифы: 
```
....
if(canvas){
  ...
  if(context){
     ...
  }
}
```

2023-05-06 04:33 UTC, EzhikTT commented on packages/client/src/Components/Game/Cell/Cell.ts
> +  setPosition(newPosition: Position) {
Для этого сеттеры есть: `set position(newPosition: Position) {this._position = newPosition}`

2023-05-06 04:33 UTC, EzhikTT commented on packages/client/src/Components/Game/Cell/Cell.ts
> +  changeColor() : string {
Этот метод должен быть публичным?

2023-05-06 04:34 UTC, EzhikTT commented on packages/client/src/Components/Game/Cell/Cell.ts
> +    this.context.textBaseline = 'middle';
Вынеси задание хардкодных значений в конструктор

2023-05-06 04:35 UTC, EzhikTT commented on packages/client/src/Components/Game/Engine/Engine.ts
> +    this.render()
Спортно. Мб не нужно рендерить сразу, как только элемент появился. Обычно, делается метод `init()` для первой отрисовки и всяких листенеров, например

2023-05-06 04:35 UTC, EzhikTT commented on packages/client/src/Components/Game/Engine/Engine.ts
> +    this.cells = [];
Почему бы это не сделать на 7 строке?

2023-05-06 04:36 UTC, EzhikTT commented on packages/client/src/Components/Game/Engine/Engine.ts
> +  generateCell(): void {
Это публичный метод?

2023-05-06 04:36 UTC, EzhikTT commented on packages/client/src/Components/Game/Engine/Engine.ts
> +    document.addEventListener("keydown", this.movingMatrixElements.bind(this));
Зачем тут `.bind`?

2023-05-06 04:37 UTC, EzhikTT commented on packages/client/src/Components/Game/Engine/Engine.ts
> +  getEmptyMatrixCoordinates() {
УБери старые методы. Этот явно внутри использует что-то, чего тут нет

2023-05-06 04:38 UTC, EzhikTT commented on packages/client/src/Components/Game/Engine/Engine.ts
> +    this.removeListeners();
Зачем удалять листенеры каждый раз?

2023-05-06 04:38 UTC, EzhikTT commented on packages/client/src/Components/Game/Engine/Engine.ts
> +  moveElement(minIndex: number, direction: string, isVertical: boolean, increasing: boolean, item: Cell|undefined): void {
Для `direction` есть перечисление

2023-05-06 04:38 UTC, EzhikTT commented on packages/client/src/Components/Game/Engine/Engine.ts
> +  moveElement(minIndex: number, direction: string, isVertical: boolean, increasing: boolean, item: Cell|undefined): void {
`item` может быть условным параметром

2023-05-06 04:39 UTC, EzhikTT commented on packages/client/src/Components/Game/Engine/Engine.ts
> +      const cellPositionX = item?.position.x;
Можно было деструктурировать `const {x: cellPositionX, y: cellPositionY} = item.position`

2023-05-06 04:40 UTC, EzhikTT commented on packages/client/src/Components/Game/Engine/Engine.ts
> +      let startIndex;
Можно было в одну строчку через запятую написать

2023-05-06 04:41 UTC, EzhikTT commented on packages/client/src/Components/Game/Engine/Engine.ts
> +      switch (isVertical) {
В таком виде использовать свитч - не красиво) В прошлый раз я говорил про использование, когда у тебя несколько строковых значений без дополнительных проверок. 
В данном случае используется `if..else` и не надо придумывать костыли)))

2023-05-06 04:45 UTC, EzhikTT commented on packages/client/src/Components/Game/Engine/Engine.ts
> +            for(let i = startIndex; i < conditionEdge; i++) {
Вот это место я совсем не понял, мне нужна пояснительная бригада: почему ты так странно обходишь чтобы найти соседа? У тебя сетка 3х3, ты знаешь что проверить и в какой плоскости, тк вариантов у тебя немного. Почему ты просто не проверяешь по индексам без цикла?

2023-05-06 04:46 UTC, EzhikTT commented on packages/client/src/Components/Game/Engine/Engine.ts
> +    this.createListeners();
Их не нужно на каждом рендере порождать. Написал про это выше про метод `init`

2023-05-06 04:47 UTC, EzhikTT commented on packages/client/src/Components/Game/Engine/Engine.ts
> +    this.generateCell();
Не уверен, что тебе нужно генерировать ячейки на каждом кадре заново

2023-05-06 04:47 UTC, EzhikTT commented on packages/client/src/Components/Game/utils/generateRandom.ts
> + export function generateRandom(min = 0, max = 100) {
Класс на улилиты создайте. Один файл лучше 100500а

2023-05-06 10:59 UTC, yppix commented on packages/client/src/Components/Game/Cell/Cell.ts
> +  setPosition(newPosition: Position) {
писала выше об этом

2023-05-06 11:00 UTC, yppix commented on packages/client/src/Components/Game/Engine/Engine.ts
> +    document.addEventListener("keydown", this.movingMatrixElements.bind(this));
сохранение контекста

2023-05-08 17:21 UTC, Brarion requested changes
Оставил один вопрос

2023-05-08 17:21 UTC, Brarion commented on packages/client/src/Components/Form/Form.tsx
> +export default Form;
Уже видел такое, хочу спросить, зачем этот компонент вообще нужен? С чем он помогает? Какую проблему решает?

2023-05-08 21:34 UTC, yppix commented on packages/client/src/Components/Form/Form.tsx
> +export default Form;
К сожалению про формы ответить не могу, они в этом МР потому что я их правила линтом, чтобы прошли тесты(

2023-05-09 03:41 UTC, EzhikTT commented on packages/client/src/Components/Form/Form.tsx
> +export default Form;
Как я понимаю, это задел на будущее. Мб это взято из программы, типа HOC. ИМХО

2023-05-09 03:43 UTC, EzhikTT commented on packages/client/src/Components/Game/Cell/Cell.ts
> +  getValue(): number {
Как и в `Engine` заменить на `get/set`

2023-05-09 03:45 UTC, EzhikTT commented on packages/client/src/Components/Game/Cell/Cell.ts
> +  private size: number;
Лучше `protected`. Скорее всего, у вас будет разделение по типам ячеек где-нибудь в будущем, поэтому класс `Cell` выглядит пригодным для наследования и полиморфизма ячеек

2023-05-09 03:48 UTC, EzhikTT commented on packages/client/src/Components/Game/Cell/Cell.ts
> +  constructor(position: Position, size: number, value?: number) {
Я скидывал раньше ссылку - https://www.koderhq.com/tutorial/typescript/get-set/ . Посмотри, мб можно конструктор написать лаконичней. НО! это просто для информации, не обязательно так делать)

2023-05-09 03:52 UTC, EzhikTT commented on packages/client/src/Components/Game/Engine/Engine.ts
> +enum Direction {
Лучше служебные вещи такие писать ДО класса, тк мы жеж читаем сверху вниз, и сразу ввести в контекст, а не искать. Плюс значение не всплывает и может не существовать в какой-то из моментов времени

2023-05-09 03:53 UTC, EzhikTT commented on packages/client/src/Components/Game/Engine/Engine.ts
> +  37: Direction.LEFT,
Что за магические числа в ключах?

2023-05-09 03:57 UTC, EzhikTT commented on packages/client/src/Components/Game/Engine/Engine.ts
> +          emptyCellExists = true;
Если здесь надо прекратить циклы, когда найдено значение(чтобы понизить сложность), то лучше взять обычный `for`:
```
for(let i = 0; !emptyCellExists && i < this._matrix.length; i++){
    for(let j = 0; !emptyCellExists && j < this._matrix[i].length; j++){
    ...
    }
}
```

2023-05-09 04:02 UTC, EzhikTT commented on packages/client/src/Components/Game/Engine/Engine.ts
> +  copyCell(position: Position, value: number): Cell {
Это лучше чтобы ячейка делала. Называется - конструктор копирования. В чистом виде вы его в ts не создадите, как в плюсах, например, но по логике это должно быть в ячейке:
```
Cell::copy(cell: Cell, cellSize?: number){
   return new Cell(cell.position, cellSize, cell.value)
}
```

2023-05-09 04:04 UTC, EzhikTT commented on packages/client/src/Components/Game/Engine/Engine.ts
> +      return;
Не имеет смысла, тк больше кода нет. В `else` оно не зайдет, если зашло в `if`

2023-05-09 04:05 UTC, EzhikTT commented on packages/client/src/Components/Game/Engine/Engine.ts
> +  checkCollision(cell1: Cell, cell2: Cell): boolean {
Позицию не надо сравнивать?

2023-05-09 04:07 UTC, EzhikTT commented on packages/client/src/Components/Game/Engine/Engine.ts
> +    try {
Зачем тут стольrо `try..catch`?

2023-05-09 04:10 UTC, EzhikTT commented on packages/client/src/Components/Game/Engine/Engine.ts
> +      case Direction.UP:
Не понимаю почему они сгруппированы так странно, те не по осям, а вот так вот. И второй блок(240 строка) нельзя использовать и тут?

2023-05-09 04:11 UTC, EzhikTT commented on packages/client/src/Components/Game/Engine/Engine.ts
> +            return isEndGame;
В такой конструкции можно было сразу `false` вернуть

2023-05-09 04:12 UTC, EzhikTT commented on packages/client/src/Components/Game/Engine/Engine.ts
> +    let isEndGame = true;
Тк у тебя несколько точек выхода из функции, тебе не нужна эта переменная для результата

2023-05-09 14:20 UTC, yppix commented on packages/client/src/Components/Game/Cell/Cell.ts
> +  private size: number;
+

2023-05-09 14:23 UTC, yppix commented on packages/client/src/Components/Game/Engine/Engine.ts
> +enum Direction {
+

2023-05-09 14:24 UTC, yppix commented on packages/client/src/Components/Game/Engine/Engine.ts
> +  37: Direction.LEFT,
коды кнопок

The keycodes are:

left = 37
up = 38
right = 39
down = 40

2023-05-09 16:49 UTC, yppix commented on packages/client/src/Components/Game/Engine/Engine.ts
> +          emptyCellExists = true;
+

2023-05-09 17:06 UTC, yppix commented on packages/client/src/Components/Game/Engine/Engine.ts
> +  copyCell(position: Position, value: number): Cell {
+

2023-05-09 17:09 UTC, yppix commented on packages/client/src/Components/Game/Engine/Engine.ts
> +    try {
чтобы он прошелся по всем элементам вверх вниз вправо влево, а если какой то элемент в указанных индексах не найден - то работа продолжилась а не отсановилась

2023-05-09 17:12 UTC, yppix commented on packages/client/src/Components/Game/Engine/Engine.ts
> +            return isEndGame;
+

2023-05-09 17:13 UTC, yppix commented on packages/client/src/Components/Game/Engine/Engine.ts
> +    let isEndGame = true;
+

2023-05-10 04:20 UTC, EzhikTT commented on packages/client/src/Components/Game/Engine/Engine.ts
> +  checkCollision(cell1: Cell, cell2: Cell): boolean {
Оки

2023-05-10 04:21 UTC, EzhikTT commented on packages/client/src/Components/Game/Engine/Engine.ts
> +    try {
А тут какие вообще исключения могут быть вообще?

2023-05-10 04:22 UTC, EzhikTT commented on packages/client/src/Components/Game/Cell/Cell.ts
> +  static copyCell(position: Position, size: number, value: number)
Не обязательно `Cell`, если он не ругается на служебное слово

2023-05-10 04:23 UTC, EzhikTT commented on packages/client/src/Components/Game/Cell/Cell.ts
> +  static copyCell(position: Position, size: number, value: number)
И в конструктор копирования нужно передать ячейку другую, а не данные для ее создания. Тогда смысла нет в конструкторе копирования

2023-05-10 12:38 UTC, Brarion approved these changes

2023-05-10 20:05 UTC, yppix commented on packages/client/src/Components/Game/Engine/Engine.ts
> +    try {
да, могут, я когда пыталась уйти от этого метода, то он выкидывал исключения вида
Engine.ts:206 Uncaught TypeError: Cannot read properties of undefined (reading '0')

2023-05-11 04:44 UTC, EzhikTT commented on packages/client/src/Components/Game/Engine/Engine.ts
> +    try {
Пример: 
```
if(i >= 0 && myArray?.length >= i && j > 0 && myArray[i]?.length >= j && myArray[i][j - 1]){
    neighbors.push(myArray[i][j - 1]);
}
```

2023-05-11 14:04 UTC, yppix commented on packages/client/src/Components/Game/Engine/Engine.ts
> +    try {
++
\+

2023-05-11 15:17 UTC, Delexy approved these changes

2023-05-11 18:03 UTC, Brarion approved these changes

2023-05-11 22:26 UTC, merged