Fri 16 (Forum Page)
friday-night-commit/2048-game pull request #21
Opened 2023-05-05 09:25 UTC by laksan1

### Какую задачу решаем
Созданы страницы: форум, добавление поста. Добавлен moment js.
Все данные берутся из файла-заглушки (packages/client/src/pages/Forum/stubs.ts).

### Скриншоты/видяшка (если есть)

https://user-images.githubusercontent.com/53944188/236422247-f2d63937-65be-4675-8adc-bb0fd35412e9.mp4

### TBD (если есть)

2023-05-05 12:49 UTC, julia-aranovich commented on packages/client/src/router.tsx
> +export default createBrowserRouter([
мне кажется, надо рауты делать внутри форума все: /forum, /forum/add-post, /forum/posts


AddPost в структуре файлов заявлена как отдельная страница, но не вижу ее использование в роутере..

2023-05-05 12:49 UTC, julia-aranovich commented on packages/client/package.json
> +    "@reduxjs/toolkit": "1.9.5",
Зачем redux  в этом патче? Давайте не смешивать задачи..
Мы потом запутаемся. К redux тогда уж и типы надо добавлять сразу и тд

2023-05-05 12:49 UTC, julia-aranovich commented on packages/client/src/pages/Forum/components/CommentsBlock/index.tsx
> +                  <span>...Skeleton</span>
У Леши в пиаре с лидербордом добавлена общая компонента загрузки данных. Можно будет ее заиспользовать потом

2023-05-05 12:49 UTC, julia-aranovich commented on packages/client/src/pages/Forum/components/SideBlock/index.tsx
> +import './index.scss';
Файл стилей пустой

2023-05-05 12:49 UTC, julia-aranovich commented on packages/client/src/pages/Forum/components/TagsBlock/index.tsx
> +            href={`/tags/${name}`}>
Мы будем поддерживать работу тегов? Тогда надо страницы под них?..

2023-05-05 12:49 UTC, julia-aranovich commented on packages/client/src/pages/Forum/index.tsx
> +                  _id={obj._id}
Мб написать короче?
`<Post {...obj} isEditable={...} />`

2023-05-05 12:49 UTC, julia-aranovich commented on packages/client/src/pages/Forum/index.tsx
> +  const data = [
tabsData?
`data`  слишком общее название...

2023-05-05 12:49 UTC, julia-aranovich commented on packages/client/src/pages/Post/index.tsx
> +    <a
Почему не  Link?

2023-05-05 12:49 UTC, julia-aranovich commented on packages/client/src/pages/Post/index.tsx
> +            <Link className="text-sm" to={`/posts/${id}/edit`}>
Сейчас в верстке получается ссылка в ссылке, это точно работает?

2023-05-05 12:49 UTC, julia-aranovich commented on packages/client/src/pages/Post/index.tsx
> +            <svg
Поддерживаю идею Николая о выносе <svg /> в иконки - тяжело читать код основных компонент

2023-05-05 13:15 UTC, Delexy commented on packages/client/src/pages/AddPost/components/TextEditor/index.tsx
Стоит ли добавлять в данный компонент кнопочки со смайлами, обёрткой кода и др.?
Просто мне кажется у нас руки до этого так и не дойдут))

2023-05-05 13:53 UTC, laksan1 commented on packages/client/src/pages/Forum/components/TagsBlock/index.tsx
> +            href={`/tags/${name}`}>
я там еще не до конца продумал, как сделать. С тегами, как будто это темы форума

2023-05-05 14:01 UTC, laksan1 commented on packages/client/src/pages/Forum/components/TagsBlock/index.tsx
> +            href={`/tags/${name}`}>
я тут думал или страницу сделать или просто фильтровать по тегу, но для фильтра нужен сразу redux , чтобы двойную работу не делать. Пока Удал
ю

2023-05-05 14:03 UTC, laksan1 commented on packages/client/src/pages/Forum/index.tsx
> +                  _id={obj._id}
про это не знал. Спасибо)

2023-05-05 14:59 UTC, laksan1 commented on packages/client/src/pages/AddPost/components/TextEditor/index.tsx
Смайлы точно нужно по заданию. Я пока сделал заглушку так, как можно использовать готовые библиотеки. Там будет все просто.

2023-05-08 17:13 UTC, Brarion requested changes

2023-05-08 17:13 UTC, Brarion commented on packages/client/src/Components/Input/index.tsx
> +  additionalClasses?: string;
Предлагаю `additionalClasses` заменить на привычный `className`
Также, думаю, было бы намного удобнее сделать этот компонент полностью управляемым, то есть передавать в него `value` и `onChange`, хотя не настаиваю

2023-05-08 17:13 UTC, Brarion commented on packages/client/src/pages/AddPost/components/TextEditor/index.tsx
> +                </svg>
Тут бы тоже `SVG` вынести, было бы супер

2023-05-08 17:13 UTC, Brarion commented on packages/client/src/pages/AddPost/index.tsx
> +    'https://upload.wikimedia.org/wikipedia/commons/a/a4/%D0%97%D0%B0%D0%BA%D0%B0%D1%82_%D0%9F%D0%B0%D0%B0%D0%BD%D0%B0%D1%8F%D1%80%D0%B2%D0%B8.jpg';
Вечную константу лучше над компонентом описать или в отдельном файле `constants.ts` , например

2023-05-08 17:13 UTC, Brarion commented on packages/client/src/pages/Post/index.tsx
> +  imageUrl,
Немного не понял, этот компонент используется в `pages/FullPost`, но тоже лежит в `pages`. Думаю, лучше этот компонент перенести в `pages/FullPost/components`

2023-05-08 17:13 UTC, Brarion commented on packages/client/src/router.tsx
> +export default createBrowserRouter([
+

2023-05-12 10:55 UTC, laksan1 commented on packages/client/src/router.tsx
> +export default createBrowserRouter([
не понял, как это делать. Закомментировал этот кусок кода

```
  {
    path: routes.forumPage,
    element: <ForumPage />,
  /*  children: [
      { path: `${routes.postsPage}/:id`, element: <FullPost /> }
    ],*/
  },
```

2023-05-12 14:43 UTC, Brarion approved these changes

2023-05-15 06:55 UTC, julia-aranovich commented on packages/client/src/routes.tsx
> +  postsPage = '/posts',
Поправь на  'posts' (без слеша), тогда можно раскоментить строки в router.tsx

2023-05-17 08:16 UTC, merged