Fri 30 (Добавить Service Workers)
friday-night-commit/2048-game pull request #30
Opened 2023-05-22 15:49 UTC by laksan1

### Какую задачу решаем
Добавить Service Workers
![image](https://github.com/friday-night-commit/2048-game/assets/53944188/cb554504-0dee-4ac3-8ea1-20e302f99011)

2023-05-22 19:20 UTC, Brarion requested changes
Оставил небольшое предложение

2023-05-22 19:20 UTC, Brarion commented on packages/client/src/App.tsx
> +  initServiceWorker();
Не встречал инициализацию `ServiceWorker` в компоненте. Обычно это делают в `main.tsx`, например, то есть там, где
```tsx
const root = ReactDOM.createRoot(document.getElementById('root') as HTMLElement);
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);

initServiceWorker();
```
`Create React App` по умолчанию тоже туда вставляет

2023-05-23 10:39 UTC, Delexy approved these changes
Совсем небольшой моментик оставил)

2023-05-23 10:39 UTC, Delexy commented on packages/client/src/ServiceWorkers/initServiceWorker.ts
> +            console.log(
Нужны ли эти строчки в "проде"?)

2023-05-23 12:28 UTC, laksan1 commented on packages/client/src/ServiceWorkers/initServiceWorker.ts
> +            console.log(
В проде нет. Просто для лога вывел, что работает. Мы же потом все равно "чистить" проект будем

2023-05-23 19:36 UTC, merged