2048 animation start end
friday-night-commit/2048-game pull request #31
Opened 2023-05-22 18:47 UTC by yppix

Анимация
Добавление экранов начала окончания игры

2023-05-22 19:17 UTC, Brarion requested changes
Несколько вопросов оставил

2023-05-22 19:17 UTC, Brarion commented on packages/client/src/pages/Game/components/FailureModal/index.tsx
> +          <Button className='game-button small' onClick={() => refreshPage()}>
Можно просто `onClick={refreshPage}`

2023-05-22 19:17 UTC, Brarion commented on packages/client/src/pages/Game/components/FailureModal/index.tsx
> +  }
Обычно в функциональных компонентах пишут так:
```ts
const refreshPage = {
  window.location.reload();
}
```
Можно ещё `React.useCallback` добавить, чтобы функция не пересоздавалась каждый раз после изменения пропсов или обновления родительских компонентов

2023-05-22 19:17 UTC, Brarion commented on packages/client/src/pages/Game/index.tsx
> +  const handleOpenFailureModal = () => !modalFailure;
А это работает? Просто выглядит, как функции, которые ничего не делают, я про то, что `actions` обычно вызываются с помощью `dispatch(action)`, а тут просто `!value`, не уверен, что `!value` засетится в стор

2023-05-22 19:17 UTC, Brarion commented on packages/client/src/Components/Game/Canvas/Canvas.tsx
> +type CanvasProps = React.DetailedHTMLProps<React.CanvasHTMLAttributes<HTMLCanvasElement>, HTMLCanvasElement> & any;
`any` очень не очень)

2023-05-22 19:17 UTC, Brarion commented on packages/client/src/Components/Game/Canvas/Canvas.tsx
> +  isOpen: state
А зачем тут `isOpen`? Или я просто не увидел?

2023-05-22 21:35 UTC, yppix commented on packages/client/src/pages/Game/components/FailureModal/index.tsx
> +          <Button className='game-button small' onClick={() => refreshPage()}>
\+

2023-05-22 21:36 UTC, yppix commented on packages/client/src/pages/Game/components/FailureModal/index.tsx
> +  }
\+

2023-05-22 21:56 UTC, yppix commented on packages/client/src/pages/Game/index.tsx
> +  const handleOpenFailureModal = () => !modalFailure;
посмотри пожалуйста новую реализацию

2023-05-22 22:00 UTC, yppix commented on packages/client/src/Components/Game/Canvas/Canvas.tsx
> +  isOpen: state
\+

2023-05-22 22:01 UTC, yppix commented on packages/client/src/Components/Game/Canvas/Canvas.tsx
> +type CanvasProps = React.DetailedHTMLProps<React.CanvasHTMLAttributes<HTMLCanvasElement>, HTMLCanvasElement> & any;
поправила по комментам - ок отрабатывает!!!

2023-05-23 16:24 UTC, Delexy requested changes

2023-05-23 16:24 UTC, Delexy commented on packages/client/src/Components/Game/Cell/Cell.ts
> +import { Utils } from '../../../../../../../../../../Desktop/кккк/Game/utils/Utils';
Думаю тут что-то поломалось)

2023-05-23 16:24 UTC, Delexy commented on packages/client/src/Components/Game/Engine/Engine.ts
> +import { Utils } from '../../../../../../../../../../Desktop/кккк/Game/utils/Utils';
И тут

2023-05-23 19:05 UTC, Brarion requested changes
Оставил предложение/вопросик

2023-05-23 19:05 UTC, Brarion commented on packages/client/src/pages/Game/index.tsx
> +  }
А вот так не получится?
```ts
  const handleOpenSuccessModal = () => dispatch(openModalSuccess());
  const handleOpenFailureModal = () =>dispatch(openModalFailure());
  const handleCloseSuccessModal = () => dispatch(closeModalSuccess());
  const handleCloseFailureModal = () =>dispatch(closeModalFailure());
```
И по идее модалки умеют только закрываться сами, а открываются они в родительском компоненте, ну или реализацию я пока что не понял)

2023-05-23 21:05 UTC, Brarion approved these changes
Ура)

2023-05-24 10:49 UTC, Delexy approved these changes

2023-05-24 10:54 UTC, merged