FRI-34: Tests for the game engine
friday-night-commit/2048-game pull request #32
Opened 2023-05-23 09:58 UTC by julia-aranovich

2023-05-23 10:52 UTC, Delexy approved these changes
Насколько я всё понял, то вроде бы всё хорошо)

2023-05-23 20:09 UTC, Brarion requested changes
Оставил несколько вопросов/замечаний/предложений)

2023-05-23 20:09 UTC, Brarion commented on packages/client/src/Components/Game/Engine/Engine.test.ts
> +  });
Тут можно вот так, чтобы избежать `as jest.Mock`
```ts
it('should add keydown listener on init', () => {
  jest.spyOn(document, 'addEventListener').mockImplementation(jest.fn)
  engine = new Engine(ctx, 200, 4);

  expect(document.addEventListener).toBeCalledTimes(1);
  expect(document.addEventListener).toBeCalledWith(
    'keydown',
    expect.any(Function)
  );

  // document.addEventListener = originalAddEventListener;
});
```
А вместо комментария сбросить мок, дальше ниже похожая история, там аналогично

2023-05-23 20:09 UTC, Brarion commented on packages/client/src/Components/Game/Engine/Engine.test.ts
> +    const position = engine.generateRandomCellPosition() as Position;
Вот тут нужно написать иначе без `as Position`. Либо рассмотреть 2 ситуации с действительно `Position` и `undefined` (2 теста), либо, если есть уверенность в `Position` добавить `if`, но лучше первый вариант, наверное

2023-05-23 20:09 UTC, Brarion commented on packages/client/src/Components/Game/Engine/Engine.test.ts
> +    const position = engine.generateRandomCellPosition() as Position;
Либо нелогично реализован `generateRandomCellPosition`, как я понял, это генерация расположения, он должен по идее работать 100%. Или я ошибаюсь?

2023-05-23 20:09 UTC, Brarion commented on packages/client/src/Components/Game/Engine/Engine.test.ts
> +    expect(result instanceof Cell).toBeTruthy();
`copyCell` возвращает по типизации `Cell`, а ниже проверяется, действительно ли полученный результат `Cell`, странно)

2023-05-23 20:09 UTC, Brarion commented on packages/client/src/Components/Game/Engine/Engine.test.ts
> +    const position = engine.generateRandomCellPosition() as Position;
Ниже тоже есть аналогичные истории

2023-05-23 20:09 UTC, Brarion commented on packages/client/src/Components/Game/Cell/Cell.test.ts
> +  });
В `Engine.test.ts` есть аналогичная история

2023-05-24 12:17 UTC, Brarion approved these changes

2023-05-25 10:47 UTC, merged