Fri 35 (Express SSR)
friday-night-commit/2048-game pull request #37
Opened 2023-06-02 12:57 UTC by laksan1

### Какую задачу решаем
Настроить Express для Server Side Rendering (без Redux, просто отдавать React-страничку).

Вопросы:
1. С какими данными сделать initialState и data?
2. Как правильно сделать функцию getPageHtml?
3. Как импортировать import { initialStore } from 'client/src/store'; в bundle.tsx?

2023-06-05 15:43 UTC, Brarion commented on packages/server/app.ts
> +const app: Express = express()
Не совсем понимаю, зачем тут типизация, просто функция `express()` сама по себе возвращает типизированное значение, но если хочется, можно оставить)

2023-06-05 16:14 UTC, Brarion requested changes
В общем описал подход и пару предложений

2023-06-05 16:14 UTC, Brarion commented on packages/server/controllers/user.ts
> +}
Это не понял, подумал, что таким образом выполнялись первые попытки)

2023-06-06 02:35 UTC, Delexy commented
Насколько я понимаю суть задания в том чтобы так же настроить hydrateRoot на клиенте? Поскольку в данный момент React-странички нет, есть просто html и тот текстом

![image](https://github.com/friday-night-commit/2048-game/assets/59692501/837f9162-7043-4e12-a78f-284204f39048)

![image](https://github.com/friday-night-commit/2048-game/assets/59692501/458952ce-286f-429a-9ab5-6821393573d3)

2023-06-06 12:44 UTC, laksan1 commented on packages/server/index.ts
> +import 'dotenv/config';
исправил на export const app = express()

2023-06-06 13:02 UTC, laksan1 commented on packages/server/middlewares/render/render.ts
> +  const html = renderBundle({
Вот тут не понял, как это реализовать

2023-06-06 13:04 UTC, laksan1 commented on packages/server/controllers/user.ts
> +}
Так точно, пользователя не стал трогать.

2023-06-08 15:05 UTC, Delexy approved these changes

2023-06-08 16:20 UTC, Brarion approved these changes

2023-06-08 19:04 UTC, julia-aranovich approved these changes

2023-06-09 05:19 UTC, merged