Add fullscreen api
friday-night-commit/2048-game pull request #39
Opened 2023-06-06 20:34 UTC by yppix

### Какую задачу решаем
Добавлние еще одного Web API на проект. В данном случае Fullscreen API

2023-06-08 17:34 UTC, yppix commented on packages/client/src/Components/Game/Canvas/index.tsx
> +      const toggler = document.getElementById('btn-fullscreen-mode') as HTMLButtonElement;
Попробовала 
![image](https://github.com/friday-night-commit/2048-game/assets/38808605/87a99b34-6993-41ee-8114-a8e1e9f93ca7)
а разметкой я же просто обращаюсь к уже созданному компоненту
но я подумала что тут реально не очень красиво, мы доп логику используем в компоненте и я вынесла в Utils этот функцинал

2023-06-09 13:33 UTC, laksan1 commented on packages/client/src/Components/Game/Utils.ts
> +      if (!document.fullscreenElement) {
я не очень уверен в таком подходе. На мой взгляд это отдельная кнопка с useCallback

https://raobotics.com/blog/react-fullscreen

2023-06-10 10:16 UTC, yppix commented on packages/client/src/Components/Game/Utils.ts
> +      if (!document.fullscreenElement) {
в итоге обсудили это в конфе

2023-06-11 20:06 UTC, Brarion requested changes
Есть вопрос, обсудим?

2023-06-11 20:06 UTC, Brarion commented on packages/client/src/Components/Game/Utils.ts
> +    const targetElem = document.getElementById('canvas-game') as HTMLCanvasElement;
Всем приветик, хочу поговорить с вами по поводу `as`, это жёсткое приведение типа, что является на самом деле (что очевидно) неприемлимым в плане хорошего кода, я понимаю, что это быстрое решение, поэтому иногда можно применять `as`, поэтому, если это очень хочется использовать, то напишите в телеге, я сразу аппрувну, если хотите перейти к более качественному решению, то нужно добавить пару проверок для успешной типизации. Хотя, в любом случае напишите в телеге, что выберете, я не против любого решения, потому что всё зависит от вас, но я против `as`

2023-06-11 20:26 UTC, Brarion approved these changes

2023-06-13 19:18 UTC, merged