Connect DB
friday-night-commit/2048-game pull request #49
Opened 2023-06-19 12:31 UTC by julia-aranovich

2023-06-20 07:06 UTC, EzhikTT commented on packages/server/api/topics.ts
> +  .route('/forum/topics/:topicId')
Лучше вынести эту строчку в файл с апи и туда импортнуть остальное в отдельном роуте

2023-06-20 07:07 UTC, EzhikTT commented on packages/server/controllers/TopicsController.ts
> +        res.status(200).json(topic.toJSON());
`toJSON()` разве не строку возвращает? А метод `json()` ожидает не массив/объект?

2023-06-20 07:08 UTC, EzhikTT commented on packages/server/controllers/TopicsController.ts
> +    try {
А почему тут не if как дальше?

2023-06-20 10:25 UTC, laksan1 commented on packages/server/controllers/TopicsController.ts
> +      return next(ApiError.badRequest(`Пост с id ${topicId} не найден`));
Тут мб любая ошибка связанная с бд. Нужно вывести error.message, а не "...не найден"

2023-06-20 10:25 UTC, laksan1 commented on packages/server/controllers/TopicsController.ts
> +      return next(ApiError.badRequest('Не получилось создать пост'));
в таком же запросе в 24 строчке выводится другая информация

2023-06-20 10:25 UTC, laksan1 commented on packages/server/controllers/TopicsController.ts
> +      if (topic) {
тут легче написать 
`if (!topic) {
res.status(404)
}
`

2023-06-20 10:25 UTC, laksan1 commented on packages/server/controllers/TopicsController.ts
> +    if (!topicId) {
обычно, чтобы не городить столько проверок делается DTO (Class-Transformer).

https://dev.to/mdmostafizurrahaman/simplifying-dto-management-in-expressjs-with-class-transformer-56mh

2023-06-20 10:25 UTC, laksan1 commented on packages/server/db/controllers/comments.ts
> +async function getCommentById(id: number): Promise<Comment | null> {
Проще сделать id, как строку в бд и не конвертировать Number(id). Унарный оператор был бы лучше для перевода из string to number 
![image](https://github.com/friday-night-commit/2048-game/assets/53944188/82f63b8e-f3a1-4e23-a4c5-5b194f9ed204)

2023-06-20 10:25 UTC, laksan1 commented on packages/server/db/controllers/topics.ts
> +async function updateTopicById(topic: ITopic) {
в методе crateTopic возвращаешь промис с топиком, а тут нет ...
Promise<Topic | null>

2023-06-20 10:25 UTC, laksan1 commented on packages/server/db/models/comment.model.ts
> +  commentId: number | null;
зачем тут id и commentId?

2023-06-20 10:25 UTC, laksan1 commented on packages/server/index.ts
> +  app.use('*', getYandexUser);
по мне лучше читается, когда 
```
app
.use(...)
.use(...)
.use(...)
```

2023-06-20 18:08 UTC, yppix commented on packages/server/controllers/TopicsController.ts
> +      return next(ApiError.badRequest(`Пост с id ${topicId} не найден`));
спорно - точно знаешь место где косяк и что именно отвалилось, но можно просто сконкатенировать в конце тип ошибку

2023-06-21 08:21 UTC, laksan1 commented on packages/server/controllers/TopicsController.ts
> +      return next(ApiError.badRequest(`Пост с id ${topicId} не найден`));
try catch не равно 404

2023-06-21 12:37 UTC, julia-aranovich commented on packages/server/controllers/CommentsController.ts
> +    if (!yandexId) {
да, однозначно тот момент стоит оптимизировать. Не знаю, как сделать это правильно с точки зрения архитектуры? Может быть @brarion может подсказать? Может быть это должна быть какая-то мидлвара, навешаннаяна урлы `/api/forum/...` ?

2023-06-21 12:37 UTC, julia-aranovich commented on packages/server/controllers/CommentsController.ts
> +        commentId
commentId является опциональным аргументом в dbCommentsController.createComment, то есть его отсутствие допускается

2023-06-21 12:37 UTC, julia-aranovich commented on packages/server/db/controllers/comments.ts
> +  topicId: number | null,
* обсудили на звонке необходимость обоих полей  commentId, topicId

2023-06-21 12:37 UTC, julia-aranovich commented on packages/server/db/models/comment.model.ts
> +  commentId: number | null;
commentId  необзодим для организации ответов на комментариев с использованием этой же таблицы comments

2023-06-21 12:37 UTC, julia-aranovich commented on packages/server/db/controllers/topics.ts
> +async function updateTopicById(topic: ITopic) {
Выглядит так, что  update метод sequalize  возвращает affectedCount  - кол-во обновленных строк в таблице
![Screenshot 2023-06-21 at 16 34 29](https://github.com/friday-night-commit/2048-game/assets/123967434/4ee399e8-0429-4aa1-91f7-8b6c80966a22)

2023-06-21 12:37 UTC, julia-aranovich commented on .eslintrc.js
> +    // '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
Временно закоментила, потому что TS почему-то считает, что импортированные из  sequalize объекты типа  Model, String и тд не используются в коде. Например, в файле packages/server/db/models/comment.model.ts

@brarion Нид ё хелп )

2023-06-21 12:38 UTC, julia-aranovich commented on packages/server/db.ts
> +// dotenv.config({path: __dirname + '../../.env'});
никак не могу заставить dotenv увидеть мой  .env  файл...

2023-06-21 16:18 UTC, Brarion commented on packages/server/controllers/CommentsController.ts
> +    if (!yandexId) {
Если это будет использовать в нескольких местах, то да, было бы круто мидлварой сделать на конкретные урлы, как ты и написала, а если в одном месте, то в целом ничего критичного

2023-06-21 16:21 UTC, Brarion commented on .eslintrc.js
> +    // '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
Давай попробуем сделать вот так: ` '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_', varsIgnorePattern: '/^_/u', }],`

2023-06-22 08:41 UTC, Brarion commented on packages/server/controllers/CommentsController.ts
> +      res.status(204).end();
Никогда не встречал `end()`, прикольно)
Можно ещё вот так `res.sendStatus(204);`, но смысл один и тот же)

2023-06-22 09:02 UTC, Brarion requested changes
В телеге большую часть обсудили, да и есть ещё комменты от коллег, жду фиксов с `dotenv`, `await`  и валидацией

2023-06-22 09:02 UTC, Brarion commented on packages/server/db/controllers/topics.ts
> +  return Topic.create({ title, text, userId });
Везде есть `await`, а тут его нет(

2023-06-22 10:42 UTC, julia-aranovich commented on packages/server/controllers/TopicsController.ts
> +    const { topicId } = req.params;
Если это не критично, оставила бы как есть. В некоторых методах есть еще  commentId, userId и тд и тп. Хочется сразу понимать, где какой id

2023-06-22 10:42 UTC, julia-aranovich commented on packages/server/controllers/TopicsController.ts
> +      if (topic) {
404  здесь не подходит. topic не был создан (а не не найден), это скорее 400

2023-06-22 10:42 UTC, julia-aranovich commented on packages/server/controllers/TopicsController.ts
> +      return next(ApiError.badRequest('Не получилось создать пост'));
Там другой запрос - там ищется топик по id, а здесь topic  новый создается

2023-06-22 10:42 UTC, julia-aranovich commented on packages/server/controllers/CommentsController.ts
> +    if (!yandexId) {
Добавила мидлвару

2023-06-23 09:25 UTC, Brarion approved these changes
Остались у коллег вопросы/предложения/замечания, а по остальному вроде ок

2023-06-23 11:33 UTC, julia-aranovich commented on packages/server/controllers/TopicsController.ts
> +      return next(ApiError.badRequest(`Пост с id ${topicId} не найден`));
Конкатенировала ошибки

2023-06-24 10:48 UTC, merged