Auth page
friday-night-commit/2048-game pull request #7
Opened 2023-04-24 03:06 UTC by Delexy

Added markup of auth page with very simple logic

2023-04-24 03:10 UTC, Delexy commented
Крайне извиняюсь за моё плохое умение работать с ветками, но если мне объясните почему у меня тянуться коммиты с другой ветки, буду премного благодарен)

2023-04-24 06:20 UTC, julia-aranovich commented on packages/client/src/pages/Auth/index.tsx
> +    console.log(formData);
Давай сделаем в самом компоненте Form  метод  onSubmit,  который будет содержать выделенную логику и вызывать хендлеры из родительских компонент, передавая в них данные формы. Тогда в хендлерах, которые будут передаваться в Form, не надо будет каждый раз повторять preventDefault и тд

2023-04-24 06:29 UTC, Delexy commented on packages/client/src/pages/Auth/index.tsx
> +    console.log(formData);
Обернуть в Form.tsx метод handleSubmit в функцию, правильно же я понимаю?)

2023-04-24 06:41 UTC, julia-aranovich commented on packages/client/src/pages/Auth/index.tsx
> +    console.log(formData);
Да, у тебя будет Form.onSubmit,  который делает e.preventDefault и вызывает this.props.handleSubmit(formData);

2023-04-24 14:04 UTC, julia-aranovich approved these changes

2023-04-24 14:24 UTC, Brarion commented on packages/client/src/router.tsx
> +    <Route path={routes.authPage} element={<Auth />}></Route>,
Закрыть бы последний `Route`)

2023-04-24 14:25 UTC, Brarion commented on packages/client/src/router.tsx
> +    <Route path={routes.authPage} element={<Auth />}></Route>,
Ну в смысле закрыть так, как закрыт первый

2023-04-24 14:33 UTC, Delexy commented on packages/client/src/router.tsx
> +    <Route path={routes.authPage} element={<Auth />}></Route>,
В смысле сделать так же как первый сделан с самозакрытием?

2023-04-25 07:47 UTC, Brarion requested changes
Супер, пару предложений оставил)

2023-04-25 07:47 UTC, Brarion commented on packages/client/src/Components/Form/Form.tsx
> +export default Form
Не совсем понимаю, что делает этот компонент. Выглядит, как просто обёртка, но смысла не вижу особого. В `pages/Auth` лежит страница, внутри есть форма, тогда почему бы не вынести форму полностью в этот компонент (с инпутами, кнопками и всем, что встретится). Так будет страница `Auth` выглядеть легче в плане нагруженности и читаемости

2023-04-25 07:47 UTC, Brarion commented on packages/client/src/pages/Auth/index.tsx
> +            <Input type="password" size="lg" label="Пароль" name='password'/>
Неуправляемые компоненты – не всегда хорошо. Думаю, для формы лучше создать состояние. Либо для каждого инпута отдельное, либо как объект с полями формы. Когда будет добавление логики валидации, отправки данных формы на сервер, будет легче работать с данными. Плюс будет дополнительная типизация всего

2023-04-25 07:47 UTC, Brarion commented on packages/client/src/router.tsx
> +}
Думаю, позже вы столкнётесь с ситуацией, когда роуте перенесёте в массив с объектами типа
```ts
{
  path: '/auth',
  component: Auth
}
```
Не настаиваю на изменение структуры, просто предлагаю обсудить с командой, как вам будет удобнее
Просто, если это будет объект, то его можно будет легко замапить, чтобы не писать кучу раз `<Route ... />

2023-04-25 18:17 UTC, Brarion requested changes

2023-04-25 18:17 UTC, Brarion commented on packages/client/src/Components/AuthForm/AuthForm.tsx
> +  const [formInputsData, setFormInputsData] = useState({
Лучше типизацию добавить. Что-то вроде следующего:
```tsx

type Form = {
  login: string;
  password: string;
}

const AuthForm = () => {
   const [formInputsData, setFormInputsData] = useState<Form>({
     login: '',
    password: '',
  })
...
```
И ещё, лично моё мнение, но `const AuthForm = () => ...` красивее, чем `function AuthForm() { ...`, но тут не важно, просто моё мнение)

2023-04-25 18:17 UTC, Brarion commented on packages/client/src/Components/AuthForm/AuthForm.tsx
> +import { FormEvent, useState } from 'react'
Хорошей практикой является разделение импортов. Зачастую библиотечные импорты выносят наверх в один блок (не разделены импорты энтером), после идут импорты какие-нибудь другие, в конце блок с импортом стилей, но лучше с командой обсудите это, если хотите прям красоту-красоту)

2023-04-25 18:17 UTC, Brarion commented on packages/client/src/Components/AuthForm/AuthForm.tsx
> +            }}
Решение с `onChange` верное, но (сейчас будет куча теории). Есть компонент `AuthForm`, у него есть состояние, как известно, компонент ререндерится при 4 случаях:
1. Изменение состояния компонента
2. Изменение пропса компонента
3. Перерендер родительского компонента
4. В случае использования классовых компонентах некоторые ленивые разработчики используют forceUpdate(), который насильно перерендеривает компонент
Когда перерендеривается компонент, создаются снова все переменные и функции (ниже пример):
```tsx
const Component = () => {
  const a = 10;

  const foo = () => {
    console.log('foo');
  }
  
  return <div>test</div>;
}
```
То есть в случае перерендера `Component` будут снова созданы `a` и `foo`. В случае, если бы в `a` лежал непримитивный тип данных, то ссылка бы стала новой. Аналогичная история повторяется в строках `29-34` в МРе. 
```tsx
onChange={event => {
  setFormInputsData({
    ...formInputsData,
    login: event.target.value,
  })
}}
```
Функция, переданная пропсом тоже будет создаваться снова. Это повлечёт за собой перерендер компонента `Input`. Это плохо
Хорошей практикой является создание отдельных функций, а не их объявление прям внутри пропса, но, это также не спасает от перерендера `Input` (в данном случае)
Для оптимизации используется мемоизация с помощью `React.useMemo()` для значений и `React.useCallback()` для функций. Если есть желание сделать супер-пупер оптимально, советую использовать, если нет, то постарайтесь функции выносить, а не объявлять в пропсах, так будет красивее

НО, я не настаиваю, можете писать так, как вам удобно)

2023-04-25 18:17 UTC, Brarion commented on packages/client/src/Components/Form/Form.tsx
> +const Form: TProps = props => {
Обычно пишут сразу так:
```tsx
type Props= {
  className?: string
  handleSubmit: (e: FormEvent<HTMLFormElement>) => void
  children?: JSX.Element | JSX.Element[]
}

const Form: React.FC<TProps> = props => {
...
}
```

2023-04-25 18:17 UTC, Brarion commented on packages/client/src/Components/Form/Form.tsx
> +}
Всё ещё мне кажется это лишней обёрткой. Если это будет использоваться для абсолютно всех форм, то какой смысл? Валидации везде будут разные. Если просто взять и удалить этот компонент, то ничего не поменяется. Напиши, пожалуйста, ещё раз (лучше в телегу), зачем это, я не понимаю(

2023-04-26 11:55 UTC, Brarion commented on packages/client/src/Components/AuthForm/AuthForm.tsx
> +  }, [formInputsData]);
Чтобы не возиться с `const inputName = event.target.getAttribute('name') as keyof Form;` можно просто 2 отдельные функции сделать для каждого инпута, но не обязательно. По крайней мере по типизации будет лучше, тк не будет `as keyof Form`

2023-04-26 11:55 UTC, Brarion approved these changes

2023-04-26 12:02 UTC, merged